export const homeData = [
    {
      id: 1,
      name: "Avengers:Endgame",
      rating: 4.7,
      time: "2hr : 22mins",
      desc: "AVENGERS: ENDGAME is set after Thanos' catastrophic use of the Infinity Stones randomly wiped out half of Earth's population in Avengers: Infinity War. Those left behind are desperate to do something -- anything -- to bring back their lost loved ones",
      starring: "—Bruce Banner, Steve Rogers, Thor, Natasha Romanoff, and James Rhodes",
      genres: "Action",
      tags: "Action, Adventures, Thriller",
      cover: "../images/im1.jpg",
      video: "../videos/MP-1.mp4",
      date: "April 26, 2019",
    },
    {
      id: 2,
      name: "EXtraction:2",
      rating: 4.6,
      time: "2hr : 3mins",
      desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
      starring: "Chris Hemsworth,Golshifteh Farahani",
      genres: "Action, Mystery & thriller",
      tags: "Adventures,Animation,Family",
      cover: "../images/im2.webp",
      video: "../videos/MP-2.mp4",
      date: "10 Jun 16, 2023",
    },
    {
      id: 3,
      name: "AVATAR: THE WAY OF WATER",
      rating: 4.8,
      time: "3hr : 12mins",
      desc: "Avatar: The Way of Water begins to tell the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
      starring: "Sam Worthington, Zoe Saldana,  Cliff Curtis ",
      genres: "Sci-fi, Adventure, Action, Fantasy",
      tags: "Adventures,Action ",
      cover: "../images/im3.jpg",
      video: "../videos/MP-3.mp4",
      date: "20-FEB-2010",
    },
    {
      id: 4,
      name: "GUARDIANS OF THE GALAXY VOL. 3",
      rating: 4.9,
      time: "2hr : 30mins",
      desc: " our beloved band of misfits are looking a bit different these days. Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
      starring: "Zoe Saldana,Dave Bautista,Karen Gillan",
      genres: "Sci-fi, Adventure, Action, Fantasy, Comedy",
      tags: "Action, Adventures",
      cover: "../images/im4.jpg",
      video: "../videos/MP-4.mp4",
      date: "May 5, 2023 ",
    },
  ]
  export const upcome = [
    {
      id: 1,
      cover: "../images/upcome/u1.jpg",
      name: "My office Boss",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "../images/upcome/u2.jpg",
      name: "Shadowe",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "../images/upcome/u3.jpg",
      name: "Another Danger",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: "../images/upcome/u4.jpg",
      name: "One Man Army",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "../images/upcome/u5.jpg",
      name: "Jumbo Queen",
      time: "2hr : 38mins",
    },
  ]
  export const latest = [
    {
      id: 1,
      cover: "../images/upcome/u6.png",
      name: "King of Jungle",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "../images/upcome/u7.jpg",
      name: "The illusion",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "../images/upcome/u1.jpg",
      name: "Latest Movie",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: "../images/upcome/u5.jpg",
      name: "Latest two",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "../images/upcome/u4.jpg",
      name: "Latest Three",
      time: "2hr : 38mins",
    },
  ]
  
  export const trending = [
    {
      id: 1,
      name: "Jurrasic Park",
      rating: 4.7,
      time: "2hr : 22mins",
      desc: "In Steven Spielberg's massive blockbuster, paleontologists Alan Grant (Sam Neill) and Ellie Sattler (Laura Dern) and mathematician Ian Malcolm (Jeff Goldblum) are among a select group chosen to tour an island theme park populated by dinosaurs created from prehistoric DNA. While the park's mastermind, billionaire John Hammond (Richard Attenborough), assures everyone that the facility is safe, they find out otherwise when various ferocious predators break free and go on the hunt.",
      starring: "Laura Dern,Richard Attenborough",
      genres: " Adventure, Action, Sci-fi, Mystery & thriller",
      tags: "Action, Adventures",
      cover: "../images/trend/images.jfif",
      date: " May 18, 2015",
    },
    {
      id: 2,
      name: "Smile",
      rating: 4.6,
      time: "2hr : 22mins",
      desc: "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter (Sosie Bacon) starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.",
      starring: "Caitlin Stasey,Kyle Gallner",
      genres: "Horror, Mystery & thriller",
      tags: "Horror",
      cover: "../images/trend/images1.webp",
      date: "Nov 15, 2022",
    },
    {
      id: 3,
      name: "Jumbo Queen",
      rating: 4.8,
      time: "2hr : 22mins",
      desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
      starring: "James Chinlund, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Action ",
      cover: "../images/img/slide3.jpg",
      date: "20-FEB-2010",
    },
  ]
  export const recommended = [
    {
      id: 4,
      cover: "../images/rec/rec1.jpg",
      name: "One Man Army",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "../images/rec/rec2.jpg",
      name: "Jumbo Queen",
      time: "2hr : 38mins",
    },
    {
      id: 1,
      cover: "../images/rec/rec3.jpg",
      name: "My office Boss",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "../images/rec/rec4.jpg",
      name: "Shadowe",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "../images/upcome/u3.jpg",
      name: "Another Danger",
      time: "2hr : 38mins",
    },
  ]